### ISSUE TITLE
Unmuting an autoplaying video prevents further videos from loading/playing

### ISSUE THREAD

**Issue by techgyver** [newmuis/amphtml-story#192] opened 2017-10-05 11:59 UTC
As discussed with @sebastianbenz: when unmuting an autoplaying video all upcoming videos will not play – even when you mute the video again. 

## Instructions:
1. Visit the [demo page](http://spiegel-techlab.de/projects/amp-story/story-videos.html)
2. Wait until the first video began to play
3. Unmute the video using the button top right
4. Navigate through the story

## Browsers tested
Chrome on Android on
- Samsung S7 Edge (OS and Chrome up to date)
- Google Pixel (OS and Chrome up to date)

## AMP Version
AMP ⚡ HTML – Version 1505999805623

**Comment by abasse** [comment] 2017-10-11 09:54
@newmuis Any update on this issue?

**Comment by newmuis** [comment] 2017-10-11 12:28
For me, the videos never load, failing to load with `ERR_INSECURE_RESPONSE`.  Navigating to the videos directly also gives me such a warning.  Can you see if fixing that helps?

**Comment by techgyver** [comment] 2017-10-11 13:17
To be more specific: 
After unmuting an playing video and navigating to the next video with autoplay I get the this is this error message: 
`[Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.]`

When keeping the videos muted the playback of all videos works perfectly.

**Comment by newmuis** [comment] 2017-10-11 13:22
Thanks for the additional details.  It's very likely a bug in the extension; do you have the exact Chrome version number?  I know Chrome has very recently made some changes around how they treat playback of unmuted videos.

**Comment by techgyver** [comment] 2017-10-11 13:26
On the S7 Edge it's `Chrome Version 61.0.3163.98`

**Comment by newmuis** [comment] 2017-10-31 14:35
This is likely a duplicate of ampproject/amphtml#11856 (although the summary is different, I believe it is the same root cause).  Feel free to reopen in the [amphtml repo](https://github.com/ampproject/amphtml) if you still experience this after that issue is resolved.

**Closed by newmuis** 2017-10-31 14:35 UTC
